### ISSUE TITLE
DCD Backend: Sporadic CORS error received by frontend

### ISSUE THREAD

**Issue by aronhoyer** [equinor/dcd#314]
When running frontend and backend locally, a CORS error is encountered some times; and some times not:

`Access to XMLHttpRequest at 'http://localhost:5000/projects' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

The issue seems to resolve itself if you refresh the browser after a while.

**Comment by valentin-krasontovitsch** [comment]
looking at this issue, it seems the problem is not directly a CORS issue.

checking the request and response headers:

![token-with-cors-and-faile](https://user-images.githubusercontent.com/15932677/156147923-2412de4f-cd2a-45c9-b780-341f7836c253.png)

we see

- no `access-control-allow-origin` header in the response
- `Bearer error="invalid_token"` in the response
- we sent an authorization header `Bearer null` in the request

looking at our backend code, and the middlewares, we see

```
  app.UseAuthentication();
  app.UseAuthorization();
  app.UseCors(_accessControlPolicyName);
```

my interpretation is that the authentication middleware runs first, sees an invalid token, says no, and never let's the CORS middleware have it's say. hence no allow origin header gets set, and the browser interprets this as a cors error.

changing the sequence to

```
  app.UseCors(_accessControlPolicyName);
  app.UseAuthentication();
  app.UseAuthorization();
```

(as btw also suggested by [some official MS docs about middlewares](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#middleware-order), look for "must appear") changes the request and response headers:

![failed-request-headers](https://user-images.githubusercontent.com/15932677/156148062-4a967343-519d-4488-90dc-b20ce4f23f01.png)

we're still sending a null token, which is invalid according to the reponse, but the cors header gets set and no CORS error triggered in the browser. yeahy.

**Comment by valentin-krasontovitsch** [comment]
now i don't know much about the console, and the sequence of logs, but based on the logs

![token-not-ready-yet](https://user-images.githubusercontent.com/15932677/156148733-857932b8-7305-4901-9a67-3b2d82ffd175.png)

it seems like the requests are run before the token is acquired by the `msal` library, as the `msal:acquireTokenSuccess` event is emitted after our requests fail.

is the log sequence a reliable indicator for when things happen, @aronhoyer ? shall I investigate further down this path? or am I on the wrong track here?
