### ISSUE TITLE
DCD: Create pipeline to create bicep script

### ISSUE THREAD

**Issue by ReedOnly** [equinor/dcd#43]

**Comment by valentin-krasontovitsch** [comment]
goal: verify deployed azure infrastructure of DCD resource group in azure dev pipeline, using bicep files that describe the desired state.

**Comment by valentin-krasontovitsch** [comment]
in azure portal navigate to resource group, choose template (automation) in the side menu, and download the template after it was generated.

this has a bit too much stuff - excluded resources:
- Microsoft.Web/sites/snapshots ("backups" of apps)
- Microsoft.Web/sites/deployments (deployment history of apps)

**Comment by valentin-krasontovitsch** [comment]
provisioning the key vault is a bit complicated - in particular if one doesn't want to hard code the object IDs in the access policies.

figured it out for the app config, wanted to repeat the pattern for an app registration, turns out app registrations don't have ARM templates as they are AD objects (or something like that) - but there is a workaround [with ARM deployments scripts](https://moimhossain.com/2020/04/03/azure-ad-app-via-arm-template-deployment-scripts/), which seems a bit involved, at least for me, as it's using powershell, so i'm gonna skip over this and leave it for the future.
