### ISSUE TITLE
DCD: Connection timed out

### ISSUE THREAD

**Issue by fredrikleknes** [equinor/dcd#436]

**Comment by fredrikleknes** [comment]
Steps to reproduce:
Load dev environment, wait about 10 secsonds and the error appears in the console window.

Been troubleshooting the issue for a few hours, but not really getting anywhere. The project doesn't seem to have any custom websocket code - websockets even appear to be disabled in 'webapp.bicep'. The error does not occur locally. It does not effect the usage of the app as far as i can tell.

**Comment by ManveerPandher** [comment]
After @ManveerPandher and @fredrikleknes took a look at the issue, it appears to happen "Occasionally". 
Different behavior on Mac (@ManveerPandher ), and Windows (@fredrikleknes)

Since this doesn't produce any issues on development, testing and production, we're moving this back to "TODO" due to its low impact.
